spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: eureka2
  #    prefer-ip-address: true
  client:
    #    registerWithEureka: true
    #    fetchRegistry: true
    service-url:
      defaultZone: http://eureka1:7211/eureka/,http://eureka2:7212/eureka/
  server:
    enable-self-preservation: false #关闭自我保护机制
    eviction-interval-timer-in-ms: 4000 #清理间隔
server:
  port: 7212
