server:
  port: 7210
  servlet:
    context-path: /bbs

spring:
  application:
    name: bbs-forum
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bbs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: HASH_MAP
  cache:
    type: Ehcache
  data:
    elasticsearch:
      cluster-nodes: 192.168.135.128:9300
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
  redis:
    database: 0
    host: 192.168.135.128
    password:
    port: 6379


elasticsearch:
  bbs:
    content:
      url: http://192.168.135.128:9200/bbs/content/_search

beetl:
  suffix: html
beetl-beetlsql:
  dev: true
beetlsql:
  basePackage: com.magpie.bbs.forum.dao

web:
  upload-path: /application/opt/upload/

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.magpie.bbs.forum.model

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    service-url:
      defaultZone: http://127.0.0.1:7211/eureka/
  server:
    enable-self-preservation: false #关闭自我保护机制
    eviction-interval-timer-in-ms: 4000 #清理间隔
  instance:
    prefer-ip-address: true
    metadata-map:
      management:
        context-path: /bbs
    health-check-url: http://localhost:${server.port}/bbs/actuator/health
    status-page-url: http://localhost:${server.port}/bbs/actuator/info
    home-page-url: http://localhost:${server.port}/

ribbon.eureka.enabled: false
bbs-user.ribbon.listOfServers: http://localhost:7310

feign.hystrix.enabled: true