server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aotuzhao/bs-config
          username: zhao199606@gmail.com
          password: zhao520LKK
          search-paths: config-test
          default-label: master
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7211/eureka/,http://127.0.0.1:7212/eureka/


